import os

import tensorflow as tf

BASE_PATH = "../data"
BASE_IMAGE_PATH = os.path.join(BASE_PATH, "words")
BATCH_SIZE = 64
PADDING_TOKEN = 99
IMAGE_WIDTH = 128
IMAGE_HEIGHT = 32
AUTOTUNE = tf.data.AUTOTUNE
IAM_HANDWRITING_DATABASE = False
PERCENTAGE_OF_TRAINING_DATA = 0.9
